# Generated by Django 2.2.4 on 2019-08-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revolico', '0002_ads_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='bperson',
            name='name_set',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='phone',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bperson',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bperson',
            name='phone',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
