# Generated by Django 2.2.4 on 2019-08-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revolico', '0004_ads_bperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='classification',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='ads',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ads',
            name='price',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bperson',
            name='ads_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='phone',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bperson',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bperson',
            name='name_set',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bperson',
            name='phone',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
