# Generated by Django 2.2.4 on 2019-08-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revolico', '0005_auto_20190809_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='bperson_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
